spring:
  application:
    name: WePlay
  datasource:
    url: jdbc:mysql://localhost:3306/weplay?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    databasePlatform: org.hibernate.dialect.MySQLInnoDialect
    database: mysql
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

security:
  basic:
    enabled: false

weplay:
  security:
    rememberMe:
      key: b59c6f146879d5528a6bf382be207b5e9e626c5c
